version: "3.9"

services:
  db:
    image: mysql:8.0.28
    container_name: mysql_db
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mini_cafe
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asiz/Seoul
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - ./db/redis:/data
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: django
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  celery_worker:
    build: .
    container_name: celery-worker
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file: .env

  celery_beat:
    build: .
    container_name: celery-beat
    restart: unless-stopped
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
    env_file: .env